[package]
name = "prison_to_json"
version = "0.1.0"
authors = ["D070527"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
regex = "1.4.1"