name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check dir
      run: ls target/release -la
    - uses: actions/upload-artifact@v2
      with:
       name: UbuntuBuild
       path: target/release/emulator

  build-windows:
   runs-on: windows-latest

   steps:
   - uses: actions/checkout@v2
   - name: Build
     run: cargo build --release --verbose
   - name: Run tests
     run: cargo test --verbose
   - uses: actions/upload-artifact@v2
     with:
      name: WindowsBuild
      path: target/release/prison_to_json.exe
